In [28]:
import pandas as pd 
data=pd.read_csv('sales_data.csv')
data=data.head(10)
condition=data['car_make']=='Toyota'
data.loc[condition,'car_make']='Toyo'

data.loc[condition, 'column_name']='replace valued'

print(data[['sale_id','car_make']])


   sale_id  car_make
0        1      Ford
1        2      Toyo
2        3  Mercedes
3        4      Toyo
4        5  Mercedes
5        6      Toyo
6        7      Toyo
7        8      Ford
8        9       BMW
9       10       BMW


In [ ]:
#array is numpy datatype 
import numpy as np
list = [10,20,30]   #list is comma separated values
#array is located contingous memory
array =[10 20 30] 

#they stay together ... they store where there is 3 empty spaces
#array uses less memory , have to be same datatype, ease to perform math in


In [37]:
import pandas as pd 
import numpy as np

a= np.array([20,30,40])
b= np.array([4])

print(a) #not comma separated values
print (b)

print(a+b)

[20 30 40]
[4]
[24 34 44]


In [43]:
a=np.array([[40,50,60],[50,30,50]])  #only one data type 
print(a)

[[40 50 60]
 [50 30 50]]


In [55]:
import numpy as np 
arr=np.array([[10,20,30,40],[50,60,70,80],[20,40,50,60]]) #this is  called matrices
print(arr)

print(arr[0:3])

[[10 20 30 40]
 [50 60 70 80]
 [20 40 50 60]]


NameError: name 'describe' is not defined

In [80]:
import numpy as np 
arr=np.array([[10,20,30,40],[40,50,60,70],[20,40,50,70]]) #this is  called matrices


print(arr[2,2])

50


In [115]:
import numpy as np 
arr=np.array([[10,20,30,40],[40,50,60,70],[20,40,50,70]]) #this is  called matrices

print(arr)
print(np.shape(arr)) #this tells you size of output 3 rows 4 columns
print(np.size(arr)) #counts the number of elements  , # of elements
print(np.ndim(arr)) # tells you have two dimensions, number of commas separated matrices?
print (arr.dtype) #teslls you type of value

print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(np.dtype(arr))
 
 

[[10 20 30 40]
 [40 50 60 70]
 [20 40 50 70]]
(3, 4)
12
2
int32
[[10 20 30 40]
 [40 50 60 70]
 [20 40 50 70]]
(3, 4)
12
2


TypeError: Cannot construct a dtype from an array

In [113]:
import numpy as np 
arr=np.array([[10,20,30,40],[40,50,60,70],[20,40,50,70]]) #this is  called matrices

print(arr.astype(float)) #converts the datatype of array
print(arr.size)
print(np.size(arr))

[[10. 20. 30. 40.]
 [40. 50. 60. 70.]
 [20. 40. 50. 70.]]
12
12


In [ ]:
Some common attributes of pandas columns (Series) include:

    .dtype → Data type of the column
    .shape → Tuple with (number of rows,)
    .size → Total number of elements
    .index → Index labels
    .name → Name of the column
    .values → Underlying NumPy array
    .nunique() → Number of unique values

In [122]:
#inspecting an array 
import numpy as np
arr = np.array([[0,2],[4,6],[6,2]])

print(np.shape(arr))
print(arr.shape)

print(arr.dtype) #tells you its int32
print(type(arr)) #tells you its as array 
print(arr.astype(float)) #converts the number to float


# Both np.shape(arr) and arr.shape give the same result because:

# np.shape(arr) is a function that returns the shape of the array.
# arr.shape is an attribute of the array that directly stores its shape.

(3, 2)
(3, 2)
int32
<class 'numpy.ndarray'>
[[0. 2.]
 [4. 6.]
 [6. 2.]]


In [139]:
#mathemetical aoperations 

import numpy as np 
data1 = np.array([[10,20],[40,50]])
data2= np.array([[10,20],[40,50]])

print(data1+data2)
print(np.add(data1,data2))

print(data1-data2)
print(np.subtract(data1,data2))

print(data1*data2)
print(np.multiply(data1,data2))

[[ 20  40]
 [ 80 100]]
[[ 20  40]
 [ 80 100]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[ 100  400]
 [1600 2500]]
[[ 100  400]
 [1600 2500]]
[[1410065408          0]
 [         0          0]]


In [141]:
import numpy as np 
arr  = np.array([1,2,3,4])
arr2 = np.array([2])

print(np.power(arr,arr2))

[ 1  4  9 16]


In [145]:
import numpy as np 
arr  = np.array([1,4,9,16])
arr2 = np.array([2])
print(np.sqrt(arr).astype(int))


[1 2 3 4]


In [146]:
#combining and splitting arrays 
#46:16
a=[10,20,30]
b=[5,5,3]

print(a+b)


[10, 20, 30, 5, 5, 3]


In [149]:
import numpy as np
a=[10,20,30]
b=[5,5,3]
a=np.array(a)
b=np.array(b)
print(a,b)
print(np.add(a,b))
print(a+b)

[10 20 30] [5 5 3]
[15 25 33]
[15 25 33]


In [153]:
#Concatenate 
import numpy as np
arr1=np.array([30,40,50])
arr2=np.array([5,5,6])

print(np.concatenate([arr1,arr2]))


[30 40 50  5  5  6]


In [176]:
#Concatenate 
import numpy as np
arr1=np.array([[2,2],[3,3]])
arr2=np.array([[2,2],[3,3]])

print(np.concatenate([arr1, arr2], axis=1))
print(np.hstack([arr1,arr2]))   #horizontal concatenation 


[[2 2 2 2]
 [3 3 3 3]]
[[2 2 2 2]
 [3 3 3 3]]


In [182]:
#Concatenate 
import numpy as np
arr1=np.array([[2,2],[3,3]])
arr2=np.array([[2,2],[3,3]])

print(np.concatenate([arr1, arr2], axis=0))
print(np.vstack([arr1,arr2]))   #vertical concatenation 

print(np.shape(arr1))
print(arr1.shape)

[[2 2]
 [3 3]
 [2 2]
 [3 3]]
[[2 2]
 [3 3]
 [2 2]
 [3 3]]
(2, 2)
(2, 2)


In [201]:
import numpy as np

a=np.array([2,2,3,3,4,4])
 
b= np.array_split(a,3)
print(b[1]) # this splits array into 3 parts and give you the 1st part . 0 , 1 , 2


[3 3]


In [ ]:
import numpy as np

a=np.array([2,2,3,3,4,4])
 
b= np.array_split(a,3)
print(b[1]) # this splits array into 3 parts and give you the 1st part . 0 , 1 , 2


In [209]:
import numpy as np
a=np.array([[2,2],[3,3]])
b=np.array([[2,2],[3,3]])

print(a )
print(np.append(a,b)) #appends into array
print(np.insert(a,1,5)) #inserts into array
print(np.delete(a,[1]))  #deletes from array

[[2 2]
 [3 3]]
[2 2 3 3 2 2 3 3]
[2 5 2 3 3]
[2 3 3]


In [214]:
import numpy as np 

a=np.array([20,40,60,80])
print(np.append(a,90))
print(np.append(a,[90,100])) #turns into one dimension and inserts the values

[20 40 60 80 90]
[ 20  40  60  80  90 100]


In [215]:
import numpy as np 

a=np.array([20,40,60,80])
print(np.insert(a,1,40))  #this appends [data, index where it will be insert, inserted value]

print(np.insert(a,1,30)) #array,index,value

[20 40 40 60 80]
[20 30 40 60 80]


In [225]:
import numpy as np 

a=np.array([[20,40],[60,80]])
print(a)
print()
print(np.insert(a,1,[30,60], axis=0)) #array,index,value #inserts in i1st axis
print()
print(np.insert(a,1,[30,60], axis=1)) #array,index,value #inserts in i1st axis
print()
print(np.insert(a,[1,2],[30,60], axis=0)) #array,index,value #inserts in i1st axis

[[20 40]
 [60 80]]

[[20 40]
 [30 60]
 [60 80]]

[[20 30 40]
 [60 60 80]]

[[20 40]
 [30 60]
 [60 80]
 [30 60]]


In [226]:
import numpy as np 

a=np.array([[20,40],[60,80]])

print(np.delete(a,1)) #it becomes 1d and then deletes 1st value



[20 60 80]


In [240]:
import numpy as np 

a=np.array([[20,40],[60,80]])
print(a)
print()
print(np.delete(a,1 )) #it becomes 1d and then deletes 1st value on the column way
print()
print(np.delete(a,1, axis=0)) #says row wise .. delete 2nd row
print()
print(np.delete(a,0, axis=0)) #row wise ..delete 1st row
print()
#this will delete 1st index 
print(np.delete(a,0, axis=1)) #column wise , delete 1st row
print()

print(np.delete(a,1, axis=1)) #column wise , delete 2nd row
 

[[20 40]
 [60 80]]

[20 60 80]

[[20 40]]

[[60 80]]

[[40]
 [80]]

[[20]
 [60]]


In [242]:
#sort 
import numpy as np

ar = np.array([[2,5,6,8,7],[2,8,5,1,3]])
print(np.sort(ar))

[[2 5 6 7 8]
 [1 2 3 5 8]]


In [254]:
#sort 
import numpy as np

ar = np.array([[2,5,6,8,7],[2,8,5,1,3]])
sr = np.array([[2,5,6,8,7],[2,8,5,1,3]])

con = np.concatenate((ar.flatten(), sr.flatten()), axis=0)
print(con)

print(np.sort(con))

[2 5 6 8 7 2 8 5 1 3 2 5 6 8 7 2 8 5 1 3]
[1 1 2 2 2 2 3 3 5 5 5 5 6 6 7 7 8 8 8 8]


In [259]:
ar = np.array([3,4,1,7,8])
 
s = np.where(ar % 2 == 0 ) 
print(s)

(array([1, 4], dtype=int64),)


In [260]:
ar = np.array([3,4,1,7,8])
 
s = np.where(ar == 4) #this looks up where the value is 4 and prints the array. answer is 1
print(s)

(array([1], dtype=int64),)


In [272]:
import numpy as np 
data = np.array([1,2,3,4])
a= np.where (data % 2 == 1)
b= np.where (data % 2)
print(a)
print(b)

# Even Numbers: Remember that even numbers give a remainder of 0 when divided by 2.
#     Think of it as "divisible by 2" → data % 2 == 0.
# Odd Numbers: Odd numbers give a remainder of 1 when divided by 2. 
#     Think of it as "not divisible by 2" → data % 2 == 1.
c= np.where (data % 2 == 0)
d= np.where (data % 1)
print(c)
print(d)

# Even Numbers: Remember that even numbers give a remainder of 0 when divided by 2.
#     Think of it as "divisible by 2" → data % 2 == 0.
# Odd Numbers: Odd numbers give a remainder of 1 when divided by 2. 
#     Think of it as "not divisible by 2" → data % 2 == 1.

(array([0, 2], dtype=int64),)
(array([0, 2], dtype=int64),)
(array([1, 3], dtype=int64),)
(array([], dtype=int64),)


In [273]:
ar = np.array([1,2,3,4,5])
ss= np.searchsorted(ar,2) #(array,'value being searched')
                        #the answer is 1 and 2 falls under 1st index
print(ss)

1


In [275]:
import numpy as np 
ar=np.array([20,30,40,50])
fa = [True, False, False, False]
new=ar[fa]
print(new)

[20]


In [280]:
import numpy as np 
ar=np.array([20,30,45,50])
fa= ar%2==1
new=ar[fa]
print(new)

[45]


In [289]:
#aggregating functions in numpy
#1:11:11

import numpy as np 
a = np.array([20,40,60,80])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.size(a)) # if you want to count ... you cna use size 
print(np.mean(a)) #get mean
print(np.cumsum(a)) #counts 1st to another 
print(np.cumprod(a))

200
80
20
4
50.0
[ 20  60 120 200]
[     20     800   48000 3840000]


In [315]:
import numpy as np 
a = np.array([20,40,60,80])
b = np.array([10,5,3,5])

price = np.array(a)
quantity  = np.array(b)

print(price, "\n", quantity)

var = (np.cumprod([price,quantity], axis =0)) #this is getting sum of bottom row
bar = (np.cumprod([price,quantity], axis =1))
car = (np.cumprod([price,quantity], axis=0)) #this is multiplying a with b 

print(car)

print(var[1].sum())
print(bar[1].sum())

[20 40 60 80] 
 [10  5  3  5]
[[ 20  40  60  80]
 [200 200 180 400]]
980
960


In [338]:
#statistical functions in numpy
#1:21:42

import numpy as np 

baked_food = [200,300,150,130,200,188] #carb content

a=np.array(baked_food)
print(np.mean(baked_food)) #sum of all/ divide number of value 
print(np.median(baked_food)) #middle value
a=  (np.sort(baked_food))
print(a)
print(a[2:4].sum()/2)


##calculating manually

194.66666666666666
194.0
[130 150 188 200 200 300]
194.0


In [ ]:

import numpy as np 

baked_food = [200,300,150,130,200,188] #carb content

a=np.array(baked_food)
print(np.mean(baked_food)) #sum of all/ divide number of value 

In [ ]:
import numpy as np

ar = np.array([2,5,6,8,7])

In [175]:
print(np.hstack([arr1,arr2]))

[[2 2 2 2]
 [3 3 3 3]]


In [167]:
import numpy as np

arr1 = np.array([[2, 2], [3, 3]])
arr2 = np.array([[2, 2], [3, 3]])

# Concatenate along axis 1 (columns)
result = np.concatenate([arr1, arr2], axis=1)
print(result)

[[2 2 2 2]
 [3 3 3 3]]


In [31]:
l1 = [20,30,40]
l2 = [20,30,40]
print(l1*l2)

TypeError: can't multiply sequence by non-int of type 'list'