In [77]:
import pandas as pd
data = pd.read_csv('dirtydata.csv')
data.loc[7,'Duration']=99 # icv
data['Duration']=data['Duration'].replace(60,61)
data['Date']=pd.to_datetime(data['Date'])
data['Date']=data['Date'].fillna('2020/12/22')

nullcalories= data[data['Calories'].isnull()]
data.loc[(18,28),'Calories']=18 #i c v . index,column = values
print(nullcalories)
data['Calories']=data['Calories'].replace(479,480)
data['Calories']=data['Calories'].astype('int')
print(data.sort_values('Calories', ascending=False))

 

    Duration       Date  Pulse  Maxpulse  Calories
18        45 2020-12-18     90       112       NaN
28        61 2020-12-28    103       132       NaN
    Duration       Date  Pulse  Maxpulse  Calories
1         61 2020-12-02    117       145       480
0         61 2020-12-01    110       130       409
4         45 2020-12-05    117       148       406
30        61 2020-12-30    102       129       380
14        61 2020-12-14    104       132       379
6         61 2020-12-07    110       136       374
21        61 2020-12-21    108       131       364
13        61 2020-12-13    106       128       345
2         61 2020-12-03    103       135       340
25        61 2020-12-25    102       126       334
10        61 2020-12-11    103       147       329
19        61 2020-12-19    103       123       323
23        61 2020-12-23    130       101       300
5         61 2020-12-06    102       127       300
17        61 2020-12-17    100       120       300
3         45 2020-12-04    109 

In [97]:
#JobReadyUdemy
import pandas as pd 

data = pd.DataFrame(
[
    ("Apple",'red','small')
]
    ,columns=["Fruit","Color","Size"]
    ,index=[2]
    
    )

print(data)
#mods

   Fruit Color   Size
2  Apple   red  small


In [99]:
import numpy as np 
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [106]:
import numpy as np 
np.arange(2,11,2)
#start,end,step

array([ 2,  4,  6,  8, 10])

In [105]:
np.linspace(1,10,10)
#start index, end index , number of items in that array
#basically segments 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [110]:
np.linspace((1,1),(10,10),10)

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.],
       [ 4.,  4.],
       [ 5.,  5.],
       [ 6.,  6.],
       [ 7.,  7.],
       [ 8.,  8.],
       [ 9.,  9.],
       [10., 10.]])

In [113]:
np.random.rand(4)

array([0.44696055, 0.23383747, 0.4188841 , 0.75074547])

In [114]:
np.random.rand(2,4)

array([[0.23270246, 0.21625233, 0.9442102 , 0.06705177],
       [0.78188723, 0.0065453 , 0.69225779, 0.10557187]])

In [115]:
np.random.randn(5)

array([ 1.50438591,  2.61095102,  0.08657949, -0.43468393,  0.76079725])

In [119]:
import numpy as np

result = np.random.choice(['head', 'tail'])
print(result)


tail


In [124]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [121]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
np.ones(1)

array([1.])

In [127]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [130]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [136]:
my_array = np.random.randn(12)
my_array

array([ 0.29475559,  0.05147049,  0.48396699, -0.1235146 , -0.5731752 ,
        0.06644185,  0.32379731,  1.89590191, -1.23759867,  0.79314823,
       -0.36317378,  1.03219462])

In [137]:
my_array.shape

(12,)

In [139]:
my_array.reshape(3,4)

array([[ 0.29475559,  0.05147049,  0.48396699, -0.1235146 ],
       [-0.5731752 ,  0.06644185,  0.32379731,  1.89590191],
       [-1.23759867,  0.79314823, -0.36317378,  1.03219462]])

In [148]:
import numpy as np
my_array= np.arange(3,9)
my_array

array([3, 4, 5, 6, 7, 8])

In [145]:
my_array[2]

5

In [152]:
data = [1,2,3]
data[1]

2

In [153]:
my_array[2:4]

array([5, 6])

In [154]:
my_array[2:]

array([5, 6, 7, 8])

In [155]:
my_array[:2]

array([3, 4])

In [156]:
my_array[-1]

8

In [166]:
slice_my_array = np.arange(3,7)
slice_my_array

array([3, 4, 5, 6])

In [168]:
slice = my_array[1:3]
slice

array([4, 5])

In [169]:
slice[:] = 25
slice

array([25, 25])

In [170]:
my_array

array([ 3, 25, 25,  6,  7,  8])

In [171]:
copy = my_array.copy()
copy

array([ 3, 25, 25,  6,  7,  8])

In [172]:
copy[1]=10
copy

array([ 3, 10, 25,  6,  7,  8])

In [173]:
my_2d = np.array([[2,3,4],[4,5,7],[3,7,7]])
my_2d

array([[2, 3, 4],
       [4, 5, 7],
       [3, 7, 7]])

In [179]:
my_2d[1]

array([4, 5, 7])

In [180]:
my_2d[1][2] #index 1 and column 2

7

In [181]:
my_2d[1,2]

7

In [182]:
my_2d[:,2] #you want all rows but column 2

array([4, 7, 7])

In [190]:
rand_array = np.random.randn(10)
bool_array = rand_array > 0
rand_array[bool_array == True]

array([1.32007171, 0.79446846, 0.77932894, 0.15346538, 0.60771882,
       0.38179814])

In [193]:
rand_array[rand_array>1]

array([1.32007171])

In [195]:
rand_array = np.random.randn(15).reshape(3,5)
rand_array

array([[ 0.80174917, -0.76273717, -0.92213643, -0.09281958, -2.15590923],
       [-0.01943135,  0.7797365 ,  0.89579701,  0.3839045 ,  0.55778701],
       [-1.23376804, -0.05903596,  1.152534  , -0.96179238, -0.78997869]])

In [197]:
rand_array[rand_array>0]

array([0.80174917, 0.7797365 , 0.89579701, 0.3839045 , 0.55778701,
       1.152534  ])

In [216]:
import pandas as pd 
import numpy as np
array  = np.random.randn(1,15).reshape(3,5)
array 

array([[-0.13570929, -0.69124786,  1.3814733 , -0.57695988, -0.18442027],
       [-0.34545807,  0.03403026,  0.59367665,  0.54588717, -0.56104355],
       [-2.10064025,  0.1869751 ,  1.56142073, -0.92932649,  0.99409337]])

In [229]:
import pandas as pd 
data = pd.DataFrame(['Cat','Dog','Elephant'])
data[data[0]=='Dog']


data.to_csv('doodoo', index=False)

In [226]:
array = np.random.randn(15).reshape(3,5)
boole = array>0
boole
array[boole>0]

array([1.46058988, 0.95861723, 0.80042716, 0.7433407 , 0.95847571,
       0.50249094, 0.1921347 ])