In [5]:
name='oi'
age='toi'
'My name is {name} and my age is {age}'.format(name='mo',age=23)

'My name is mo and my age is 23'

In [8]:
print('My name is {name} and my age is {age}'.format(name='mo',age=23))

My name is mo and my age is 23


In [9]:
print(name)

oi


In [19]:
s='abcdefghijk'
s[2:4]

'cd'

In [22]:
s=['hi',1,[1,2]]
s[2][1]

2

In [24]:
s=[1,2,3]
a=['a','b','c']
a.append('d')
print(a)
a[3]

['a', 'b', 'c', 'd']


'd'

In [29]:
a=[1,2,3,4,5]
print(a[a[0]='My'])
 


SyntaxError: invalid syntax (838876563.py, line 2)

In [31]:
nest = [1,2,[3,4],5]
nest[2]

[3, 4]

In [33]:
nest = [1,2,3,[4,5,['target']]]
nest[3][2]

['target']

In [42]:
data = {"apple": (1, 2, 3)}  # Dictionary with a tuple as a value
data

{'apple': (1, 2, 3)}

In [44]:
data = (("apple": (1, 2, 3)))  # Tuple of tuples
print(data)

SyntaxError: invalid syntax (1289415617.py, line 1)

In [52]:
d= {'k1':[1,2,3]}
d['k1'][2]

3

In [56]:
t = [1,2,3]
t[0] = 'oi'
t

['oi', 2, 3]

In [58]:
#Sets = unique elements

In [59]:
a = {1,2,3,4,1,2,3,4,5,6}
a

{1, 2, 3, 4, 5, 6}

In [61]:
a= (1,2,3,4,5,1,1,2,3,4,5,6,1,2,3)
print(set(a))

{1, 2, 3, 4, 5, 6}


In [66]:
s={1,2,3,4}
s.add(6)
s

{1, 2, 3, 4, 6}

In [67]:
1>2

False

In [68]:
1>=1

True

In [69]:
1>1

False

In [70]:
 1 == 1

True

In [73]:
1!=2

True

In [75]:
'hi' != 'bye'

True

In [81]:
if 1<2:
    print('yes')
    

yes


In [92]:
if 3!>2:
    print('yes')
elif 1>2:
     print('2nd')
else:
    print('something wrong')
            
        

SyntaxError: invalid syntax (1455954068.py, line 1)

In [97]:
person = {
    "name": 'Rehan',
    'age': 35,
    'Address':{
        'city':'houston',
        'state':'texas',
        'country':'usa'}
    ,'car':'toyota'
      }
print(person['Address']['state'])

texas


In [98]:
seq = [1,2,3,4]
for i in seq:
    print(i)

1
2
3
4


In [ ]:
for variable in range:
    #code block
    
while condition:
    #code block

In [102]:
i=1
while i < 100:
    print(i)
    i=i+10

1
11
21
31
41
51
61
71
81
91


In [106]:
i = 1 
 
while i <5:
    print('i is: {}'.format(i))
    i+=1

I is: 1
I is: 2
I is: 3
I is: 4


In [107]:
for x in seq:
    print(x)

1
2
3
4


In [108]:
for x in range(1,5):
    print(x)

1
2
3
4


In [109]:
range(0,5)

range(0, 5)

In [116]:
x=list(range(5))
out=  []
for num in x:
    out.append(num**2)
print(num)


4


In [115]:
[item ** 2 for item in x]

[0, 1, 4, 9, 16]

In [117]:
def my_func(param1):
    print(param1)
my_func('hello')

hello


In [119]:
def function_name(parameter_name):
    print(parameter_name)

    
print(function_name('parameter_name'))

parameter_name
None


In [130]:
def function(name='default'): #can have a default value
    print('Hello ' +name)

function()

Hello default


In [131]:
def square(num):
    return num**2

output=square(2)
output

4

In [133]:
def square(value): #function name(variable name)
    return value+6 #the actual calculation gets placed here
output=square(2) #square is name o function 
                    #when you do return .. you have to set variable to that function and
                    #then you call that variable
output

8

In [137]:
def square(value): #function name(variable name)
   """
can have a multi line comment with three double quotes 
this makes it easy to type 
this is called documentaion string"""

return value+6 #the actual calculation gets placed here

output=square(2) #square is name o function 
                    #when you do return .. you have to set variable to that function and
                    #then you call that variable
output

SyntaxError: 'return' outside function (64714190.py, line 7)

In [139]:
#5:57PM Section 3 Part 4
# lambda expressions

def times2(var):
    return var*2

times2(2)

4

In [143]:
#map
seq = [1,2,3,4,5]

list(map(times2, seq))


[2, 4, 6, 8, 10]

In [145]:
t = lambda var:var*2
t(6)

12

In [148]:
list(map(lambda num: num*2, seq))

[2, 4, 6, 8, 10]

In [149]:
import numpy as np 
data = np.random.randint(1,10,10)


array([1, 7, 6, 4, 6, 8, 1, 4, 1, 3])

In [150]:
t = list(map(lambda x:x+2, data))
t


[3, 9, 8, 6, 8, 10, 3, 6, 3, 5]

In [156]:
seq = [1,2,3,4,5]
list(filter(lambda num: num%2==1, seq)) num%2==1

[1, 3, 5]

In [157]:
s= 'hello my name is sam'
s.lower()

'hello my name is sam'

In [159]:
s= 'hello my name is sam'
print(s.upper())

HELLO MY NAME IS SAM


In [160]:
s.split()

['hello', 'my', 'name', 'is', 'sam']

In [187]:
d={'k1':1,'k2':2}
d.items()


dict_items([('k1', 1), ('k2', 2)])

In [193]:
list = [1,2,3]
oi=list.pop()
list
oi

3

In [207]:
data = [1,2,3]
data.append(5)
data

[1, 2, 3, 5]

In [208]:
x=[(1,2),(3,4),(5,6)]
x[0][1]

2

In [209]:
for item in x:
    print(item)

(1, 2)
(3, 4)
(5, 6)


In [216]:
for a,b in x:
    print(a)

1
3
5


In [222]:
#numpy 2/26 3:15PM
import numpy as np 
s = np.array([1,2,3])
s1 = np.random.randint(1,10,10).
s
s1

In [225]:
my_list=[1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [226]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [227]:
np.arange(1,10,1)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [233]:
np.linspace(0,5,num=5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])